# Generated by Django 4.1 on 2024-04-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date'], 'verbose_name': 'محتوی', 'verbose_name_plural': ' محتوی'},
        ),
    ]
